from typing import Protocol, Optional

from src.domain.entities.tasks import Task


class TaskRepositoryInterface(Protocol):
    async def get_by_id(self, task_id: int) -> Optional[Task]: ...

    async def get_user_tasks_trees(self, user_id: int) -> list[Task]: ...

    async def get_task_tree(self, from_task_id: int) -> Optional[Task]: ...

    async def delete_task(self, task_id: int) -> None: ...
