from typing import Protocol, Optional

from src.domain.entities.tasks import Task


class TaskRepositoryInterface(Protocol):
    async def get_by_id(self, task_id: int) -> Optional[Task]: ...

    async def get_with_parents(self, task_id: int) -> Task: ...

    async def get_with_parent_and_subs(self, task_id: int) -> Task: ...

    async def get_active_tasks(self, user_id: int, page: int = 1,
                               size: int = 5) -> tuple[int, int, list[Task]]: ...

    async def get_finished_tasks(self, user_id: int, page: int = 1,
                                 size: int = 5) -> tuple[int, int, list[Task]]: ...

    async def get_subtasks(self, parent_id: int, page: int = 1,
                           size: int = 5) -> tuple[Optional[int], int, list[Task]]: ...

    async def get_task_with_subtasks(self, from_task_id: int) -> Task: ...

    async def get_task_tree(self, from_task_id: int) -> Task: ...

    async def delete_task(self, task_id: int) -> None: ...
