services:
  tracker_backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
    depends_on:
      - database
      - tracker_backend_redis
    
  database:
    image: postgres:14.6-alpine
    volumes:
      - tracker_backend_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  tracker_backend_redis:
    image: redis:7.0.5-alpine
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - tracker_backend_redis_data:/data

  tracker_backend_worker:
    build:  
      context: .
    env_file:
      - .env
    command: celery -A celery_app worker --loglevel=info --concurrency=${CELERY_WORKERS} -Q ${TASK_SERVICE_QUEUE}
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - tracker_backend_redis

  flower:
    image: mher/flower:1.2.0
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - tracker_backend_redis
      - tracker_backend_worker


volumes:
  tracker_backend_redis_data:
  tracker_backend_db_data:
